// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Beliebte Werkzeuge',
    tools: [
      {
        href: '/src/pages/pdf-multi-tool.html',
        name: 'PDF Multi-Tool',
        icon: 'pencil-ruler',
        subtitle: 'Zusammenführen, Aufteilen, Organisieren, Löschen, Drehen, Leere Seiten hinzufügen, Extrahieren und Duplizieren in einer einheitlichen Oberfläche.',
      },
      {
        id: 'merge',
        name: 'PDF zusammenführen',
        icon: 'combine',
        subtitle: 'Combine multiple PDFs into one file. Preserves Bookmarks.',
      },
      {
        id: 'split',
        name: 'PDF aufteilen',
        icon: 'scissors',
        subtitle: 'Seitenbereich in eine neue PDF extrahieren.',
      },
      {
        id: 'compress',
        name: 'PDF komprimieren',
        icon: 'zap',
        subtitle: 'Dateigröße Ihrer PDF reduzieren.',
      },
      {
        id: 'edit',
        name: 'PDF-Editor',
        icon: 'pocket-knife',
        subtitle:
          'Annotieren, Hervorheben, Schwärzen, Kommentieren, Formen/Bilder hinzufügen, Suchen und PDFs anzeigen',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG zu PDF',
        icon: 'image-up',
        subtitle: 'PDF aus einem oder mehreren JPG-Bildern erstellen.',
      },
      {
        id: 'sign-pdf',
        name: 'PDF unterschreiben',
        icon: 'pen-tool',
        subtitle: 'Zeichnen, Tippen oder Hochladen Ihrer Unterschrift.',
      },
      {
        id: 'cropper',
        name: 'PDF zuschneiden',
        icon: 'crop',
        subtitle: 'Ränder jeder Seite in Ihrer PDF trimmen.',
      },
      {
        id: 'extract-pages',
        name: 'Seiten extrahieren',
        icon: 'ungroup',
        subtitle: 'Seitenauswahl als neue Dateien speichern.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplizieren & Organisieren',
        icon: 'files',
        subtitle: 'Seiten duplizieren, neu anordnen und löschen.',
      },
      {
        id: 'delete-pages',
        name: 'Seiten löschen',
        icon: 'trash-2',
        subtitle: 'Bestimmte Seiten aus Ihrem Dokument entfernen.',
      },
    ],
  },
  {
    name: 'Bearbeiten & Kommentieren',
    tools: [
      {
        id: 'edit',
        name: 'PDF-Editor',
        icon: 'pocket-knife',
        subtitle:
          'Annotieren, Hervorheben, Schwärzen, Kommentieren, Formen/Bilder hinzufügen, Suchen und PDFs anzeigen.',
      },
      {
        // id: 'bookmark-pdf',
        href: '/src/pages/bookmark.html',
        name: 'Lesezeichen bearbeiten',
        icon: 'bookmark',
        subtitle: 'PDF-Lesezeichen hinzufügen, bearbeiten, importieren, löschen und extrahieren.',
      },
      {
        href: '/src/pages/table-of-contents.html',
        name: 'Inhaltsverzeichnis',
        icon: 'list',
        subtitle: 'Inhaltsverzeichnis-Seite aus PDF-Lesezeichen generieren.',
      },
      {
        id: 'add-page-numbers',
        name: 'Seitenzahlen',
        icon: 'list-ordered',
        subtitle: 'Seitenzahlen in Ihr Dokument einfügen.',
      },
      {
        id: 'add-watermark',
        name: 'Wasserzeichen hinzufügen',
        icon: 'droplets',
        subtitle: 'Text oder Bild über Ihre PDF-Seiten stempeln.',
      },
      {
        id: 'add-header-footer',
        name: 'Kopf- & Fußzeile',
        icon: 'pilcrow',
        subtitle: 'Text oben und unten auf Seiten hinzufügen.',
      },
      {
        id: 'invert-colors',
        name: 'Farben invertieren',
        icon: 'contrast',
        subtitle: 'Eine "Dunkelmodus"-Version Ihrer PDF erstellen.',
      },
      {
        id: 'change-background-color',
        name: 'Hintergrundfarbe',
        icon: 'palette',
        subtitle: 'Die Hintergrundfarbe Ihrer PDF ändern.',
      },
      {
        id: 'change-text-color',
        name: 'Textfarbe ändern',
        icon: 'type',
        subtitle: 'Die Farbe des Textes in Ihrer PDF ändern.',
      },
      {
        id: 'sign-pdf',
        name: 'PDF unterschreiben',
        icon: 'pen-tool',
        subtitle: 'Zeichnen, Tippen oder Hochladen Ihrer Unterschrift.',
      },
      {
        href: '/src/pages/add-stamps.html',
        name: 'Stempel hinzufügen',
        icon: 'stamp',
        subtitle: 'Bildstempel zu Ihrer PDF mit der Annotationswerkzeugleiste hinzufügen.',
      },
      {
        id: 'remove-annotations',
        name: 'Annotationen entfernen',
        icon: 'eraser',
        subtitle: 'Kommentare, Hervorhebungen und Links entfernen.',
      },
      {
        id: 'cropper',
        name: 'PDF zuschneiden',
        icon: 'crop',
        subtitle: 'Ränder jeder Seite in Ihrer PDF trimmen.',
      },
      {
        id: 'form-filler',
        name: 'PDF-Formular ausfüllen',
        icon: 'square-pen',
        subtitle: 'Formulare direkt im Browser ausfüllen. Unterstützt auch XFA-Formulare.',
      },
      {
        href: '/src/pages/form-creator.html',
        name: 'PDF-Formular erstellen',
        icon: 'file-input',
        subtitle: 'Ausfüllbare PDF-Formulare mit Drag-and-Drop-Textfeldern erstellen.',
      },
      {
        id: 'remove-blank-pages',
        name: 'Leere Seiten entfernen',
        icon: 'file-minus-2',
        subtitle: 'Leere Seiten automatisch erkennen und löschen.',
      },
    ],
  },
  {
    name: 'In PDF konvertieren',
    tools: [
      {
        id: 'image-to-pdf',
        name: 'Bild zu PDF',
        icon: 'images',
        subtitle: 'JPG, PNG, WebP, BMP, TIFF, SVG, HEIC zu PDF konvertieren.',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG zu PDF',
        icon: 'image-up',
        subtitle: 'PDF aus einem oder mehreren JPG-Bildern erstellen.',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG zu PDF',
        icon: 'image-up',
        subtitle: 'PDF aus einem oder mehreren PNG-Bildern erstellen.',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP zu PDF',
        icon: 'image-up',
        subtitle: 'PDF aus einem oder mehreren WebP-Bildern erstellen.',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG zu PDF',
        icon: 'pen-tool',
        subtitle: 'PDF aus einem oder mehreren SVG-Bildern erstellen.',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP zu PDF',
        icon: 'image',
        subtitle: 'PDF aus einem oder mehreren BMP-Bildern erstellen.',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC zu PDF',
        icon: 'smartphone',
        subtitle: 'PDF aus einem oder mehreren HEIC-Bildern erstellen.',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF zu PDF',
        icon: 'layers',
        subtitle: 'PDF aus einem oder mehreren TIFF-Bildern erstellen.',
      },
      {
        id: 'txt-to-pdf',
        name: 'Text zu PDF',
        icon: 'file-pen',
        subtitle: 'Eine Textdatei in eine PDF konvertieren.',
      },
      {
        href: '/src/pages/json-to-pdf.html',
        name: 'JSON zu PDF',
        icon: 'file-code',
        subtitle: 'JSON-Dateien in PDF-Format konvertieren.',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: 'Von PDF konvertieren',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF zu JPG',
        icon: 'file-image',
        subtitle: 'Jede PDF-Seite in ein JPG-Bild konvertieren.',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF zu PNG',
        icon: 'file-image',
        subtitle: 'Jede PDF-Seite in ein PNG-Bild konvertieren.',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF zu WebP',
        icon: 'file-image',
        subtitle: 'Jede PDF-Seite in ein WebP-Bild konvertieren.',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF zu BMP',
        icon: 'file-image',
        subtitle: 'Jede PDF-Seite in ein BMP-Bild konvertieren.',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF zu TIFF',
        icon: 'file-image',
        subtitle: 'Jede PDF-Seite in ein TIFF-Bild konvertieren.',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF zu Graustufen',
        icon: 'palette',
        subtitle: 'Alle Farben in Schwarz-Weiß konvertieren.',
      },
      {
        href: '/src/pages/pdf-to-json.html',
        name: 'PDF zu JSON',
        icon: 'file-code',
        subtitle: 'PDF-Dateien in JSON-Format konvertieren.',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: 'Organisieren & Verwalten',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR PDF',
        icon: 'scan-text',
        subtitle: 'PDF durchsuchbar und kopierbar machen.',
      },
      {
        id: 'merge',
        name: 'PDF zusammenführen',
        icon: 'combine',
        subtitle: 'Mehrere PDFs zu einer Datei kombinieren.',
      },
      {
        id: 'alternate-merge',
        name: 'Seiten abwechselnd mischen',
        icon: 'shuffle',
        subtitle: 'Merge PDFs by alternating pages from each PDF. Preserves Bookmarks',
      },
      {
        id: 'organize',
        name: 'PDF organisieren',
        icon: 'grip',
        subtitle: 'Seiten per Drag-and-Drop neu anordnen.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplizieren & Organisieren',
        icon: 'files',
        subtitle: 'Seiten duplizieren, neu anordnen und löschen.',
      },
      {
        id: 'add-attachments',
        name: 'Anhänge hinzufügen',
        icon: 'paperclip',
        subtitle: 'Eine oder mehrere Dateien in Ihre PDF einbetten.',
      },
      {
        id: 'extract-attachments',
        name: 'Anhänge extrahieren',
        icon: 'download',
        subtitle: 'Alle eingebetteten Dateien aus PDF(s) als ZIP extrahieren.',
      },
      {
        id: 'edit-attachments',
        name: 'Anhänge bearbeiten',
        icon: 'file-edit',
        subtitle: 'Anhänge in Ihrer PDF anzeigen oder entfernen.',
      },
      {
        href: '/src/pages/pdf-multi-tool.html',
        name: 'PDF Multi-Tool',
        icon: 'pencil-ruler',
        subtitle: 'Voll ausgestatteter PDF-Editor mit Seitenverwaltung.',
      },
      {
        id: 'split',
        name: 'PDF aufteilen',
        icon: 'scissors',
        subtitle: 'Seitenbereich in eine neue PDF extrahieren.',
      },
      {
        id: 'split-in-half',
        name: 'Seiten teilen',
        icon: 'table-columns-split',
        subtitle: 'Seiten horizontal oder vertikal teilen.',
      },
      {
        id: 'extract-pages',
        name: 'Seiten extrahieren',
        icon: 'ungroup',
        subtitle: 'Seitenauswahl als neue Dateien speichern.',
      },
      {
        id: 'delete-pages',
        name: 'Seiten löschen',
        icon: 'trash-2',
        subtitle: 'Bestimmte Seiten aus Ihrem Dokument entfernen.',
      },
      {
        id: 'add-blank-page',
        name: 'Leere Seite hinzufügen',
        icon: 'file-plus-2',
        subtitle: 'Eine leere Seite an beliebiger Stelle in Ihrer PDF einfügen.',
      },
      {
        id: 'reverse-pages',
        name: 'Seiten umkehren',
        icon: 'arrow-down-z-a',
        subtitle: 'Die Reihenfolge aller Seiten in Ihrem Dokument umkehren.',
      },
      {
        id: 'rotate',
        name: 'PDF drehen',
        icon: 'rotate-cw',
        subtitle: 'Seiten in 90-Grad-Schritten drehen.',
      },
      {
        id: 'n-up',
        name: 'N-Up PDF',
        icon: 'layout-grid',
        subtitle: 'Mehrere Seiten auf einem einzelnen Blatt anordnen.',
      },
      {
        id: 'combine-single-page',
        name: 'Zu einer Seite kombinieren',
        icon: 'unfold-vertical',
        subtitle: 'Alle Seiten zu einem durchgehenden Scroll zusammenfügen.',
      },
      {
        id: 'view-metadata',
        name: 'Metadaten anzeigen',
        icon: 'info',
        subtitle: 'Die versteckten Eigenschaften Ihrer PDF einsehen.',
      },
      {
        id: 'edit-metadata',
        name: 'Metadaten bearbeiten',
        icon: 'file-cog',
        subtitle: 'Autor, Titel und andere Eigenschaften ändern.',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDFs zu ZIP',
        icon: 'stretch-horizontal',
        subtitle: 'Mehrere PDF-Dateien in ein ZIP-Archiv packen.',
      },
      {
        id: 'compare-pdfs',
        name: 'PDFs vergleichen',
        icon: 'git-compare',
        subtitle: 'Zwei PDFs nebeneinander vergleichen.',
      },
      {
        id: 'posterize',
        name: 'PDF posterisieren',
        icon: 'notepad-text-dashed',
        subtitle: 'Eine große Seite in mehrere kleinere Seiten aufteilen.',
      },
    ],
  },
  {
    name: 'Optimieren & Reparieren',
    tools: [
      {
        id: 'compress',
        name: 'PDF komprimieren',
        icon: 'zap',
        subtitle: 'Dateigröße Ihrer PDF reduzieren.',
      },
      {
        id: 'fix-dimensions',
        name: 'Seitengröße korrigieren',
        icon: 'ruler-dimension-line',
        subtitle: 'Alle Seiten auf einheitliche Größe standardisieren.',
      },
      {
        id: 'linearize',
        name: 'PDF linearisieren',
        icon: 'gauge',
        subtitle: 'PDF für schnelle Web-Anzeige optimieren.',
      },
      {
        id: 'page-dimensions',
        name: 'Seitenmaße',
        icon: 'ruler',
        subtitle: 'Seitengröße, Ausrichtung und Einheiten analysieren.',
      },
      {
        id: 'remove-restrictions',
        name: 'Einschränkungen entfernen',
        icon: 'unlink',
        subtitle:
          'Passwortschutz und Sicherheitseinschränkungen von digital signierten PDF-Dateien entfernen.',
      },
    ],
  },
  {
    name: 'PDF sichern',
    tools: [
      {
        id: 'encrypt',
        name: 'PDF verschlüsseln',
        icon: 'lock',
        subtitle: 'Ihre PDF durch Hinzufügen eines Passworts sperren.',
      },
      {
        id: 'sanitize-pdf',
        name: 'PDF bereinigen',
        icon: 'brush-cleaning',
        subtitle: 'Metadaten, Annotationen, Skripte und mehr entfernen.',
      },
      {
        id: 'decrypt',
        name: 'PDF entschlüsseln',
        icon: 'unlock',
        subtitle: 'PDF durch Entfernen des Passwortschutzes entsperren.',
      },
      {
        id: 'flatten',
        name: 'PDF reduzieren',
        icon: 'layers',
        subtitle: 'Formularfelder und Annotationen nicht-bearbeitbar machen.',
      },
      {
        id: 'remove-metadata',
        name: 'Metadaten entfernen',
        icon: 'file-x',
        subtitle: 'Versteckte Daten aus Ihrer PDF entfernen.',
      },
      {
        id: 'change-permissions',
        name: 'Berechtigungen ändern',
        icon: 'shield-check',
        subtitle: 'Benutzerberechtigungen für eine PDF festlegen oder ändern.',
      },
    ],
  },
];
